name: "GitHub App Token"
description: "Run GitHub Actions as a GitHub App instead of using secrets.GITHUB_TOKEN or a personal access token."
author: "Ichinose Shogo"
inputs:
  provider-endpoint:
    description: "URL for credential provider"
    required: false
  app-id:
    description: "GitHub Apps ID"
    required: false
outputs:
  token:
    description: An installation token for the GitHub App on the requested repository.
runs:
  using: "node16"
  main: "action/lib/index.js"
  post: "action/lib/cleanup.js"
  post-if: always()
branding:
  icon: "unlock"
  color: "blue"
