name: reviewdog
on: [pull_request]

permissions:
  contents: read
  pull-requests: write

jobs:
  actionlint:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: reviewdog/action-actionlint@v1
