name: deploy to staging
on:
  push:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      statuses: write
      contents: read
    environment: staging

    steps:
      - name: Check out code
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2

      - name: Set up Go
        uses: actions/setup-go@4d34df0c2316fe8122ab82dc22947d607c0c91f9 # v4.0.0
        with:
          cache: true
          go-version-file: provider/github-app-token/go.mod
          cache-dependency-path: provider/github-app-token/go.sum

      - name: build
        run: |
          make build
        working-directory: provider

      - uses: fuller-inc/actions-aws-assume-role@ee49a108ae9920a17c4abf0931f30935fea2d2b0 # v1.5.3
        with:
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::616212855146:role/github-app-token-github-actions-us-east-1
          role-session-tagging: true
          use-node-id: true

      - name: deploy
        run: |
          make deploy
        working-directory: provider
        env:
          APP_ENV: staging

      - name: Set up Node.js
        uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c # v3.6.0
        with:
          node-version: "16.x"
          cache: "npm"
          cache-dependency-path: action/package-lock.json

      - name: Install dependencies
        run: |
          npm ci
        working-directory: action

      - name: Build
        run: |
          npm run build
        working-directory: action

      - id: generate
        name: Use the action
        uses: ./
        with:
          provider-endpoint: https://8y6823l0x3.execute-api.us-east-1.amazonaws.com
          app-id: "263885"
          repositories: |
            R_kgDOIeornQ
            R_kgDOIevBqQ

      - name: Check out code
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
        with:
          repository: 'shogo82148/improved-lamp'
          path: improved-lamp
          token: ${{ steps.generate.outputs.token }}
