name: test
on:
  push:
  pull_request:

jobs:
  provider:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      id-token: write
      contents: read
    environment: development
    steps:
      - name: Checkout
        uses: actions/checkout@83b7061638ee4956cf7545a6f7efe594e5ad0247 # v3.5.1

      - name: Set up Go
        uses: actions/setup-go@4d34df0c2316fe8122ab82dc22947d607c0c91f9 # v4.0.0
        with:
          cache: true
          go-version-file: provider/github-app-token/go.mod
          cache-dependency-path: provider/github-app-token/go.sum

      - name: Test
        run: |
          make test
        working-directory: provider/github-app-token

  action:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 15
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@83b7061638ee4956cf7545a6f7efe594e5ad0247 # v3.5.1

      - name: Set up Go
        uses: actions/setup-go@4d34df0c2316fe8122ab82dc22947d607c0c91f9 # v4.0.0
        with:
          cache: true
          go-version-file: provider/github-app-token/go.mod
          cache-dependency-path: provider/github-app-token/go.sum

      - name: Set up Node.js
        uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c # v3.6.0
        with:
          node-version: "16.x"
          cache: "npm"
          cache-dependency-path: action/package-lock.json

      - name: Install dependencies
        run: |
          npm ci
        working-directory: action

      - name: Test
        run: |
          npm run test
        working-directory: action
